# Generated by Django 4.2.2 on 2023-07-02 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('completo', models.CharField(max_length=100)),
                ('fundacion', models.DateField()),
                ('ligas', models.IntegerField(default=0)),
                ('nacionales', models.IntegerField(default=0)),
                ('internacionales', models.IntegerField(default=0)),
                ('ciudad', models.CharField(max_length=100)),
                ('apodo', models.CharField(max_length=50)),
                ('estadio', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.CharField(max_length=5)),
                ('resultadoLocal', models.IntegerField(blank=True, null=True)),
                ('resultadoVisitante', models.IntegerField(blank=True, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtureLocal', to='AppFutbolArg.equipos')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtureVisitante', to='AppFutbolArg.equipos')),
            ],
            options={
                'verbose_name_plural': 'Fixture',
            },
        ),
        migrations.CreateModel(
            name='Prode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultadoLocal', models.IntegerField()),
                ('resultadoVisitante', models.IntegerField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFutbolArg.fixture')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('partidosJugados', models.IntegerField(default=0)),
                ('equipo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppFutbolArg.equipos')),
            ],
            options={
                'verbose_name_plural': 'Posiciones',
            },
        ),
    ]
