# Generated by Django 4.2.2 on 2023-07-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbolArg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posiciones',
            name='empatados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posiciones',
            name='ganados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posiciones',
            name='perdidos',
            field=models.IntegerField(default=0),
        ),
    ]
