# Generated by Django 4.2.2 on 2023-07-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbolArg', '0002_posiciones_empatados_posiciones_ganados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posiciones',
            name='difgol',
            field=models.IntegerField(default=0),
        ),
    ]
