# Generated by Django 4.2.2 on 2023-07-05 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbolArg', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
