# Generated by Django 4.2.2 on 2023-07-06 02:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFutbolArg', '0007_perfil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Perfiles',
        ),
        migrations.AlterModelOptions(
            name='perfiles',
            options={'verbose_name_plural': 'Perfiles'},
        ),
    ]
