# Generated by Django 4.2.2 on 2023-07-06 19:27

import AppFutbolArg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbolArg', '0008_rename_perfil_perfiles_alter_perfiles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(upload_to=AppFutbolArg.models.blog_image_path),
        ),
        migrations.DeleteModel(
            name='Perfiles',
        ),
    ]
