# Generated by Django 4.2.2 on 2023-07-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbolArg', '0010_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name_plural': 'Avatar'},
        ),
    ]
