# Generated by Django 4.2.2 on 2023-07-08 23:41

import AppFutbolArg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbolArg', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=AppFutbolArg.models.autor_image_path),
        ),
    ]
