# Generated by Django 4.2.2 on 2023-07-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppFutbolArg', '0014_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('enviado', models.DateTimeField(auto_now_add=True)),
                ('privado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFutbolArg.userprofile')),
                ('receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='AppFutbolArg.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Mensajes',
            },
        ),
    ]
