# Generated by Django 4.2.2 on 2023-07-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbolArg', '0014_userprofile_avatar'),
        ('AppForoArg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensaje',
            new_name='Mensajes',
        ),
    ]
