# Generated by Django 4.2.2 on 2023-07-10 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppForoArg', '0003_alter_mensajes_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='privado',
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='receptor',
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
